"""add_superadmin_and_org_status

Revision ID: 272b2a745744
Revises: f41686d7a0d8
Create Date: 2026-03-02 06:09:14.642065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '272b2a745744'
down_revision: Union[str, None] = 'f41686d7a0d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('status', sa.String(), server_default='active', nullable=False))
    op.add_column('profiles', sa.Column('is_superadmin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_superadmin')
    op.drop_column('organizations', 'status')
    # ### end Alembic commands ###
